#!/usr/bin/env python3
"""Turn CHANGELOG.md into every other place release notes have to appear.

CHANGELOG.md is written once, by hand. Everything else that shows release
notes is generated from it by this tool, so the three surfaces — the website,
the plugin's update dialog, and GitHub — can never drift apart:

    python tools/make-changelog.py               # regenerate site block + feed notes
    python tools/make-changelog.py --check       # exit 1 if any generated output is stale
    python tools/make-changelog.py --release-body 1.4.0
                                                 # markdown body for the GitHub release

What it writes
--------------
    docs/goasynth/index.html    the "Release notes" block between the changelog:begin /
                       changelog:end markers: one heading, lede and bullet list
                       per RELEASED version, plus a download row of direct
                       GitHub asset links under the newest one. [Unreleased]
                       stays local — the site never advertises a build that is
                       not packaged yet.

    --download-row auto|always|never
                       whether that newest-section download row is shown at
                       all. "auto" (the default) shows it only when the
                       release's ZIP asset is actually downloadable: while a
                       version has no GitHub release yet the row is omitted,
                       and once the Release workflow has created the assets
                       it appears — the workflow regenerates and commits the
                       page itself, so main lands the row the moment the
                       files it links exist. "always" shows it unconditionally
                       and "never" hides it; both need no network. Fail-open
                       on probe errors keeps an offline run stable.
    docs/version.json  "notes": the released latest version's bullets as plain
                       strings, which the plugin's update-available dialog
                       shows under "What's new". "latest" is kept in sync with
                       the newest released version in CHANGELOG.md, which also
                       supplies "released" (its date, printed the way the site
                       prints it) and "installer_size" (the size of its
                       GoaSynth-Setup asset, probed from the GitHub release —
                       omitted until the Release workflow has attached the
                       file, and left alone when the probe cannot answer; the
                       dialog degrades without both).

Format (see CHANGELOG.md's header for the full contract)
--------------------------------------------------------
    ## [1.4.0] - 2026-10-02        a released version
    ## [Unreleased]                work since the last release
    ### Added | Changed | Fixed    category subsections with "- " bullets
    A plain paragraph right after a version heading becomes the lede the site
    shows. Inline **bold** and `code` render on the site; they are stripped
    from the feed notes.

Plain Python 3, no third-party modules, nothing to install.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHANGELOG = ROOT / "CHANGELOG.md"
INDEX = ROOT / "docs" / "goasynth" / "index.html"
FEED = ROOT / "docs" / "version.json"

BEGIN = "<!-- changelog:begin — generated by tools/make-changelog.py from CHANGELOG.md; edit that, not this -->"
END = "<!-- changelog:end -->"

SITE_INDENT = "        "
RELEASES_URL = "https://github.com/DakaGoa/GoaSynth/releases"

MONTHS = ["", "January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December"]

HEADING = re.compile(r"^## \[(.+?)\](?: - (\d{4}-\d{2}-\d{2}))?\s*$")
CATEGORY = re.compile(r"^### (.+?)\s*$")


def parse_changelog(text: str) -> list[dict]:
    """Return the versions in file order (newest first), each as:
       {"tag": "1.4.0" | "Unreleased", "date": "2026-10-02" | "",
        "lede": str, "notes": [(category, bullet), ...]}."""
    versions: list[dict] = []
    current: dict | None = None
    pending_category = ""

    for raw in text.splitlines():
        line = raw.rstrip()

        heading = HEADING.match(line)
        if heading:
            current = {"tag": heading.group(1), "date": heading.group(2) or "",
                       "lede": "", "notes": []}
            versions.append(current)
            pending_category = ""
            continue

        if current is None:
            continue  # prose before the first heading (the file's own header)

        if line.startswith("## "):
            current = None  # an h1 or a stray h2 ends the section
            continue

        category = CATEGORY.match(line)
        if category:
            pending_category = category.group(1)
            continue

        if line.startswith("- "):
            if pending_category:
                current["notes"].append((pending_category, line[2:].strip()))
            continue

        if (line.strip() and not pending_category
                and not line.startswith(("###", "##"))):
            # Prose: the paragraph right after a version heading is the lede;
            # wrapped lines join it.
            if current["lede"]:
                current["lede"] += " " + line.strip()
            else:
                current["lede"] = line.strip()

    return versions


def inline_to_html(text: str) -> str:
    """Escape for HTML, then honour **bold** and `code`."""
    text = (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    return text


def inline_to_plain(text: str) -> str:
    """Strip the inline markdown the feed notes cannot carry."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    return text


def pretty_date(iso: str) -> str:
    if not iso:
        return ""
    y, m, d = (int(p) for p in iso.split("-"))
    return f"{d} {MONTHS[m]} {y}"


_row_probe_done = False
_row_probe_result = True


def row_is_published(tag: str) -> bool:
    """True when the release's ZIP asset is already downloadable.

    Used by --download-row auto so the site never points at assets that do
    not exist yet: the Release workflow regenerates the page after it has
    created the GitHub release, and that regeneration is the one that lands
    on main with the row. One probe per run, cached.

    A clean 404 is a real answer — before the Release workflow has created
    the release this is exactly what comes back, and hiding the row is
    correct and reproducible. Anything ambiguous (DNS failure, timeout,
    rate limit, 5xx) fails open and shows the row: an offline --check on a
    page that already carries the row must stay green, and a page that
    hides a live download is worse than one that briefly links a forming
    one.
    """
    global _row_probe_done, _row_probe_result
    if not _row_probe_done:
        url = f"{RELEASES_URL}/download/v{tag}/GoaSynth-{tag}-win64.zip"
        try:
            with urllib.request.urlopen(url, timeout=10) as response:
                _row_probe_result = response.status == 200
        except urllib.error.HTTPError as error:
            _row_probe_result = error.code != 404
        except Exception:
            _row_probe_result = True
        _row_probe_done = True
    return _row_probe_result


def human_size(num_bytes: int) -> str:
    """22939648 -> "21.9 MB": the form the update dialog shows."""
    if num_bytes >= 1024 ** 3:
        return f"{num_bytes / 1024 ** 3:.1f} GB"
    if num_bytes >= 1024 ** 2:
        return f"{num_bytes / 1024 ** 2:.1f} MB"
    return f"{num_bytes / 1024:.0f} kB"


_size_probe_done = False
_size_probe_value = None    # "21.9 MB", or None when absent / unknown
_size_probe_known = False   # the probe got an authoritative answer (200 or clean 404)


def probe_installer_size(tag: str) -> tuple[bool, str | None]:
    """(known, size) for the release's GoaSynth-Setup-<tag>.exe asset.

    A HEAD on the asset's download URL answers with its Content-Length, so
    the update dialog can say how big the download is without the plugin
    growing a second network path. One probe per run, cached, same
    philosophy as row_is_published: a clean 404 (no release yet) is a real
    answer — known-absent, so a stale size from an older version is dropped
    instead of being mislabelled; anything ambiguous (DNS, timeout, rate
    limit, odd response) is unknown — callers keep whatever the feed
    already says, and an offline --check stays stable.
    """
    global _size_probe_done, _size_probe_value, _size_probe_known
    if not _size_probe_done:
        url = f"{RELEASES_URL}/download/v{tag}/GoaSynth-Setup-{tag}.exe"
        try:
            request = urllib.request.Request(url, method="HEAD")
            with urllib.request.urlopen(request, timeout=10) as response:
                length = response.headers.get("Content-Length", "")
                if length.isdigit():
                    _size_probe_value = human_size(int(length))
                    _size_probe_known = True
        except urllib.error.HTTPError as error:
            if error.code == 404:
                _size_probe_known = True   # no asset yet: authoritative
        except Exception:
            pass                           # unknown
        _size_probe_done = True
    return _size_probe_known, _size_probe_value


def download_row(tag: str) -> list[str]:
    """Direct links to the published GitHub assets, so the newest section of
    the release notes doubles as the download page. Gated by --download-row:
    the asset URLs exist only once the Release workflow has created the
    release, and auto mode waits for exactly that."""
    base = f"{RELEASES_URL}/download/v{tag}"
    return [
        '<p class="release-downloads">'
        f'<span class="dl-label">Download {tag}</span>'
        f'<a href="{base}/GoaSynth-{tag}-win64.zip">ZIP package</a>'
        '<span class="sep">·</span>'
        f'<a href="{base}/GoaSynth-Setup-{tag}.exe">Installer</a>'
        '<span class="sep">·</span>'
        f'<a href="{base}/SHA256SUMS.txt">SHA-256 checksums</a>'
        '<span class="sep">·</span>'
        f'<a href="{RELEASES_URL}/tag/v{tag}">all files</a>'
        '</p>',
    ]


def render_site_block(versions: list[dict], indent: str = "",
                      row_mode: str = "auto") -> str:
    """The HTML between the markers: released versions, newest first."""
    out = []
    downloads_shown = False
    for v in versions:
        if v["tag"] == "Unreleased":
            continue
        date_html = f' <span class="ver-date">{pretty_date(v["date"])}</span>' if v["date"] else ""
        # Each heading carries id="vX.Y.Z" so a deep link (#vX.Y.Z) lands
        # directly on that version's notes — the update-available dialog
        # links there; #whats-new (the section wrapper) lists them all.
        out.append(f"<h2 id=\"v{v['tag']}\">What's new in {v['tag']}{date_html}</h2>")
        if v["lede"]:
            out.append('<p class="section-lede">')
            out.append(f"          {inline_to_html(v['lede'])}")
            out.append("</p>")
        if v["notes"]:
            out.append('<ul class="changelog">')
            for category, bullet in v["notes"]:
                out.append(f'  <li><span class="cat">{category}</span> '
                           f"{inline_to_html(bullet)}</li>")
            out.append("</ul>")
        # The download row rides under the newest released version only —
        # that is the one people download; older sections stay pure history.
        if not downloads_shown:
            downloads_shown = True
            if row_mode == "always" or (row_mode == "auto"
                                        and row_is_published(v["tag"])):
                out.extend(download_row(v["tag"]))
    if indent:
        out = [(indent + line) if line else line for line in out]
    return "\n".join(out)


def splice_index(html_block: str) -> bool:
    """Replace the marker block in docs/goasynth/index.html. True if it changed."""
    page = INDEX.read_text(encoding="utf-8")
    start = page.find(BEGIN)
    end = page.find(END)
    if start < 0 or end < 0 or end < start:
        raise SystemExit("docs/goasynth/index.html has no changelog:begin/end markers - "
                         "add them around the release-notes block first")
    start += len(BEGIN)
    updated = page[:start] + "\n" + html_block + "\n      " + page[end:]
    if updated == page:
        return False
    INDEX.write_text(updated, encoding="utf-8", newline="\n")
    return True


def released(versions: list[dict]) -> list[dict]:
    return [v for v in versions if v["tag"] != "Unreleased"]


def update_feed(versions: list[dict]) -> bool:
    """Sync version.json: latest = newest released; notes = its bullets;
    released = its date; installer_size = its Setup asset's size."""
    rel = released(versions)
    if not rel:
        raise SystemExit("CHANGELOG.md has no released version - nothing to publish")
    newest = rel[0]
    feed = json.loads(FEED.read_text(encoding="utf-8"))
    changed = False

    if feed.get("latest") != newest["tag"]:
        feed["latest"] = newest["tag"]
        changed = True

    notes = [inline_to_plain(bullet) for _cat, bullet in newest["notes"]]
    if feed.get("notes") != notes:
        feed["notes"] = notes
        changed = True

    # The two facts the update dialog names alongside the notes: when the
    # version shipped (straight from the heading's date) and how big its
    # installer is (probed). Unknown (offline) never deletes — the probe
    # failing must not eat a correct value; known-absent (clean 404 before
    # the Release workflow has attached the file) must — a stale size for a
    # previous version mislabelled as the new one is misinformation.
    released_at = pretty_date(newest["date"])
    if released_at and feed.get("released") != released_at:
        feed["released"] = released_at
        changed = True
    if not released_at and "released" in feed:
        del feed["released"]
        changed = True

    size_known, size = probe_installer_size(newest["tag"])
    if size_known and size and feed.get("installer_size") != size:
        feed["installer_size"] = size
        changed = True
    if size_known and not size and "installer_size" in feed:
        del feed["installer_size"]
        changed = True

    if changed:
        FEED.write_text(json.dumps(feed, indent=2, ensure_ascii=False) + "\n",
                        encoding="utf-8", newline="\n")
    return changed


def release_body(versions: list[dict], tag: str) -> str:
    for v in versions:
        if v["tag"] == tag:
            lines = [f"## GoaSynth {v['tag']}" + (f" — {pretty_date(v['date'])}" if v["date"] else ""), ""]
            if v["lede"]:
                lines += [v["lede"], ""]
            for category, bullet in v["notes"]:
                lines.append(f"- **{category}.** {bullet}")
            return "\n".join(lines)
    raise SystemExit(f"no version {tag} in CHANGELOG.md")


def check(versions: list[dict], row_mode: str = "auto") -> int:
    """--check: every generated artefact must match its source. Exit 1 if not."""
    problems = []

    page = INDEX.read_text(encoding="utf-8")
    start, end = page.find(BEGIN), page.find(END)
    if start < 0 or end < 0:
        problems.append("docs/goasynth/index.html is missing the changelog:begin/end markers")
    else:
        want = "\n" + render_site_block(versions, SITE_INDENT, row_mode) + "\n      "
        have = page[start + len(BEGIN):end]
        if have != want:
            problems.append("docs/goasynth/index.html release notes are stale - "
                            "run: python tools/make-changelog.py")

    rel = released(versions)
    feed = json.loads(FEED.read_text(encoding="utf-8"))
    if feed.get("latest") != rel[0]["tag"]:
        problems.append(f'docs/version.json latest ("{feed.get("latest")}") is not the '
                        f'newest released version ("{rel[0]["tag"]}") - '
                        "run: python tools/make-changelog.py")
    notes = [inline_to_plain(b) for _c, b in rel[0]["notes"]]
    if feed.get("notes") != notes:
        problems.append('docs/version.json "notes" are stale - '
                        "run: python tools/make-changelog.py")

    want_released = pretty_date(rel[0]["date"])
    if feed.get("released") != (want_released or None):
        problems.append('docs/version.json "released" is stale - '
                        f'(feed "{feed.get("released")}" vs CHANGELOG '
                        f'"{want_released or "-"}") - '
                        "run: python tools/make-changelog.py")

    size_known, want_size = probe_installer_size(rel[0]["tag"])
    if size_known and feed.get("installer_size") != want_size:
        problems.append('docs/version.json "installer_size" is stale - '
                        f'(feed "{feed.get("installer_size")}" vs probe '
                        f'"{want_size or "-"}") - '
                        "run: python tools/make-changelog.py")

    for problem in problems:
        print("changelog-check: " + problem)
    if problems:
        return 1
    checked = "site block, feed notes and latest (" + rel[0]["tag"] + ")"
    if want_released:
        checked += ", released date"
    if size_known:
        checked += " and installer size"
    print("changelog-check: " + checked + " all match CHANGELOG.md")
    return 0


def main() -> int:
    # A Windows console may not be able to print every character the notes
    # carry (cp1252 has no ✕ or ▸): never die on output — degrade to ?.
    if hasattr (sys.stdout, "reconfigure"):
        sys.stdout.reconfigure (encoding="utf-8", errors="replace")

    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="verify generated outputs are current; exit 1 if not")
    parser.add_argument("--release-body", metavar="X.Y.Z",
                        help="print the markdown body for a GitHub release")
    parser.add_argument("--download-row", choices=["auto", "always", "never"],
                        default="auto",
                        help="show the newest section's download row: auto "
                             "(default) = only once the GitHub release's ZIP "
                             "asset is downloadable, so a version with no "
                             "release yet ships without dead links; always or "
                             "never forces it without touching the network")
    args = parser.parse_args()

    versions = parse_changelog(CHANGELOG.read_text(encoding="utf-8"))
    if not versions:
        raise SystemExit("CHANGELOG.md parses to no versions - check its headings")

    if args.release_body:
        print(release_body(versions, args.release_body))
        return 0

    if args.check:
        return check(versions, args.download_row)

    changed_index = splice_index(render_site_block(versions, SITE_INDENT,
                                                   args.download_row))
    changed_feed = update_feed(versions)
    newest = released(versions)[0]["tag"]
    if changed_index:
        print("docs/goasynth/index.html: release notes regenerated from CHANGELOG.md")
    if changed_feed:
        print(f"docs/version.json: latest {newest} + its notes written")
    if not changed_index and not changed_feed:
        print(f"already up to date (latest {newest})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
