#!/usr/bin/env python3
"""Turn CHANGELOG.md into every other place release notes have to appear.

CHANGELOG.md is written once, by hand. Everything else that shows release
notes is generated from it by this tool, so the three surfaces — the website,
the plugin's update dialog, and GitHub — can never drift apart:

    python tools/make-changelog.py               # regenerate site block + feed notes
    python tools/make-changelog.py --check       # exit 1 if any generated output is stale
    python tools/make-changelog.py --release-body 1.4.0
                                                 # markdown body for the GitHub release

What it writes
--------------
    docs/index.html    the "Release notes" block between the changelog:begin /
                       changelog:end markers: one heading, lede and bullet list
                       per RELEASED version. [Unreleased] stays local — the site
                       never advertises a build that is not packaged yet.
    docs/version.json  "notes": the released latest version's bullets as plain
                       strings, which the plugin's update-available dialog
                       shows under "What's new". "latest" is kept in sync with
                       the newest released version in CHANGELOG.md.

Format (see CHANGELOG.md's header for the full contract)
--------------------------------------------------------
    ## [1.4.0] - 2026-10-02        a released version
    ## [Unreleased]                work since the last release
    ### Added | Changed | Fixed    category subsections with "- " bullets
    A plain paragraph right after a version heading becomes the lede the site
    shows. Inline **bold** and `code` render on the site; they are stripped
    from the feed notes.

Plain Python 3, no third-party modules, nothing to install.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHANGELOG = ROOT / "CHANGELOG.md"
INDEX = ROOT / "docs" / "index.html"
FEED = ROOT / "docs" / "version.json"

BEGIN = "<!-- changelog:begin — generated by tools/make-changelog.py from CHANGELOG.md; edit that, not this -->"
END = "<!-- changelog:end -->"

SITE_INDENT = "        "

MONTHS = ["", "January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December"]

HEADING = re.compile(r"^## \[(.+?)\](?: - (\d{4}-\d{2}-\d{2}))?\s*$")
CATEGORY = re.compile(r"^### (.+?)\s*$")


def parse_changelog(text: str) -> list[dict]:
    """Return the versions in file order (newest first), each as:
       {"tag": "1.4.0" | "Unreleased", "date": "2026-10-02" | "",
        "lede": str, "notes": [(category, bullet), ...]}."""
    versions: list[dict] = []
    current: dict | None = None
    pending_category = ""

    for raw in text.splitlines():
        line = raw.rstrip()

        heading = HEADING.match(line)
        if heading:
            current = {"tag": heading.group(1), "date": heading.group(2) or "",
                       "lede": "", "notes": []}
            versions.append(current)
            pending_category = ""
            continue

        if current is None:
            continue  # prose before the first heading (the file's own header)

        if line.startswith("## "):
            current = None  # an h1 or a stray h2 ends the section
            continue

        category = CATEGORY.match(line)
        if category:
            pending_category = category.group(1)
            continue

        if line.startswith("- "):
            if pending_category:
                current["notes"].append((pending_category, line[2:].strip()))
            continue

        if (line.strip() and not pending_category
                and not line.startswith(("###", "##"))):
            # Prose: the paragraph right after a version heading is the lede;
            # wrapped lines join it.
            if current["lede"]:
                current["lede"] += " " + line.strip()
            else:
                current["lede"] = line.strip()

    return versions


def inline_to_html(text: str) -> str:
    """Escape for HTML, then honour **bold** and `code`."""
    text = (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    return text


def inline_to_plain(text: str) -> str:
    """Strip the inline markdown the feed notes cannot carry."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    return text


def pretty_date(iso: str) -> str:
    if not iso:
        return ""
    y, m, d = (int(p) for p in iso.split("-"))
    return f"{d} {MONTHS[m]} {y}"


def render_site_block(versions: list[dict], indent: str = "") -> str:
    """The HTML between the markers: released versions, newest first."""
    out = []
    for v in versions:
        if v["tag"] == "Unreleased":
            continue
        date_html = f' <span class="ver-date">{pretty_date(v["date"])}</span>' if v["date"] else ""
        out.append(f"<h2>What's new in {v['tag']}{date_html}</h2>")
        if v["lede"]:
            out.append('<p class="section-lede">')
            out.append(f"          {inline_to_html(v['lede'])}")
            out.append("</p>")
        if v["notes"]:
            out.append('<ul class="changelog">')
            for category, bullet in v["notes"]:
                out.append(f'  <li><span class="cat">{category}</span> '
                           f"{inline_to_html(bullet)}</li>")
            out.append("</ul>")
    if indent:
        out = [(indent + line) if line else line for line in out]
    return "\n".join(out)


def splice_index(html_block: str) -> bool:
    """Replace the marker block in docs/index.html. True if it changed."""
    page = INDEX.read_text(encoding="utf-8")
    start = page.find(BEGIN)
    end = page.find(END)
    if start < 0 or end < 0 or end < start:
        raise SystemExit("docs/index.html has no changelog:begin/end markers - "
                         "add them around the release-notes block first")
    start += len(BEGIN)
    updated = page[:start] + "\n" + html_block + "\n      " + page[end:]
    if updated == page:
        return False
    INDEX.write_text(updated, encoding="utf-8", newline="\n")
    return True


def released(versions: list[dict]) -> list[dict]:
    return [v for v in versions if v["tag"] != "Unreleased"]


def update_feed(versions: list[dict]) -> bool:
    """Sync version.json: latest = newest released, notes = its bullets."""
    rel = released(versions)
    if not rel:
        raise SystemExit("CHANGELOG.md has no released version - nothing to publish")
    newest = rel[0]
    feed = json.loads(FEED.read_text(encoding="utf-8"))
    changed = False

    if feed.get("latest") != newest["tag"]:
        feed["latest"] = newest["tag"]
        changed = True

    notes = [inline_to_plain(bullet) for _cat, bullet in newest["notes"]]
    if feed.get("notes") != notes:
        feed["notes"] = notes
        changed = True

    if changed:
        FEED.write_text(json.dumps(feed, indent=2, ensure_ascii=False) + "\n",
                        encoding="utf-8", newline="\n")
    return changed


def release_body(versions: list[dict], tag: str) -> str:
    for v in versions:
        if v["tag"] == tag:
            lines = [f"## GoaSynth {v['tag']}" + (f" — {pretty_date(v['date'])}" if v["date"] else ""), ""]
            if v["lede"]:
                lines += [v["lede"], ""]
            for category, bullet in v["notes"]:
                lines.append(f"- **{category}.** {bullet}")
            return "\n".join(lines)
    raise SystemExit(f"no version {tag} in CHANGELOG.md")


def check(versions: list[dict]) -> int:
    """--check: every generated artefact must match its source. Exit 1 if not."""
    problems = []

    page = INDEX.read_text(encoding="utf-8")
    start, end = page.find(BEGIN), page.find(END)
    if start < 0 or end < 0:
        problems.append("docs/index.html is missing the changelog:begin/end markers")
    else:
        want = "\n" + render_site_block(versions, SITE_INDENT) + "\n      "
        have = page[start + len(BEGIN):end]
        if have != want:
            problems.append("docs/index.html release notes are stale - "
                            "run: python tools/make-changelog.py")

    rel = released(versions)
    feed = json.loads(FEED.read_text(encoding="utf-8"))
    if feed.get("latest") != rel[0]["tag"]:
        problems.append(f'docs/version.json latest ("{feed.get("latest")}") is not the '
                        f'newest released version ("{rel[0]["tag"]}") - '
                        "run: python tools/make-changelog.py")
    notes = [inline_to_plain(b) for _c, b in rel[0]["notes"]]
    if feed.get("notes") != notes:
        problems.append('docs/version.json "notes" are stale - '
                        "run: python tools/make-changelog.py")

    for problem in problems:
        print("changelog-check: " + problem)
    if problems:
        return 1
    print(f"changelog-check: site block, feed notes and latest "
          f"({rel[0]['tag']}) all match CHANGELOG.md")
    return 0


def main() -> int:
    # A Windows console may not be able to print every character the notes
    # carry (cp1252 has no ✕ or ▸): never die on output — degrade to ?.
    if hasattr (sys.stdout, "reconfigure"):
        sys.stdout.reconfigure (encoding="utf-8", errors="replace")

    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="verify generated outputs are current; exit 1 if not")
    parser.add_argument("--release-body", metavar="X.Y.Z",
                        help="print the markdown body for a GitHub release")
    args = parser.parse_args()

    versions = parse_changelog(CHANGELOG.read_text(encoding="utf-8"))
    if not versions:
        raise SystemExit("CHANGELOG.md parses to no versions - check its headings")

    if args.release_body:
        print(release_body(versions, args.release_body))
        return 0

    if args.check:
        return check(versions)

    changed_index = splice_index(render_site_block(versions, SITE_INDENT))
    changed_feed = update_feed(versions)
    newest = released(versions)[0]["tag"]
    if changed_index:
        print("docs/index.html: release notes regenerated from CHANGELOG.md")
    if changed_feed:
        print(f"docs/version.json: latest {newest} + its notes written")
    if not changed_index and not changed_feed:
        print(f"already up to date (latest {newest})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
