#!/usr/bin/env python3
"""Generate the site's crawl files and its absolute URLs from the pages.

Four places repeat the site's address, and every one of them is easy to leave
behind when it moves: robots.txt, sitemap.xml, the absolute URLs in each page's
head (og:url, og:image, twitter:image) and the URLs inside the landing page's
JSON-LD. None of them is written by hand:

    python tools/make-site-index.py           # rewrite them if they drifted
    python tools/make-site-index.py --check   # fail if they would change

Where the facts come from
-------------------------
The pages say where they live. Every .html file under docs/ declares its own
address in <link rel="canonical">, and those declarations are the only input:

  * sitemap.xml lists exactly them;
  * the Sitemap: line in robots.txt names the sitemap beside the canonical of
    the site root, which is also the base every og:image is built on;
  * og:url in a page's head is rewritten to that page's own canonical, so the
    head cannot disagree with the canonical link beside it;
  * og:image and twitter:image are re-rooted at the site base, keeping the
    asset path they already have (see SITE_IMAGE below);
  * every URL inside a page's JSON-LD block is re-rooted the same way, so the
    structured data cannot advertise an address the site has left.

So a new page is picked up by being a page, and moving the site to a custom
domain is: edit the canonical links, run this, commit. Nothing else knows the
host.

The one asset path that is not in the pages
-------------------------------------------
SITE_IMAGE is the shared social-preview image, named here rather than in five
files. Change it here when the screenshot it points at changes; the pages are
rewritten from this constant. It is a path under the site root, not a URL.

JSON-LD needs no such list, which is why there is not one. The block names its
own site URL - the "url" of its WebSite node - so this tool re-roots every URL
in the block by replacing that prefix, wherever the block references it: the
@id fragments, the offer URL, the app URL, the image and the screenshot list.
Screenshot paths stay where a person reads them, in the page, and adding a
fourth screenshot is a page edit rather than a tool edit. The block is parsed
before and after the rewrite, so a malformed one cannot be written.

What it refuses
---------------
  * a page with no canonical link, or with more than one;
  * a canonical that is not an absolute https:// URL;
  * pages claiming two different origins - the sitemap can only advertise one,
    so that is a page to fix, not a value to guess at;
  * a page with no og:url, or an og:image that is not absolute;
  * a JSON-LD block that is not valid JSON, or that names no site URL to re-root;
  * a missing docs/index.html, or a docs/ with no pages in it.

The output is deterministic - sorted, LF endings, no timestamps - so re-running
it over an unchanged tree rewrites identical bytes and says so. tests/DocsCheck
compares the same values during the test suite; this tool exists so that a
failure is a one-command fix rather than a hand edit.

Plain Python 3, no third-party modules, nothing to install.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
ROBOTS = DOCS / "robots.txt"
SITEMAP = DOCS / "sitemap.xml"

# The social-preview image every page shares, as a path under the site root.
SITE_IMAGE = "assets/ui-overview.png"

CANONICAL = re.compile(r'<link\s+rel="canonical"\s+href="([^"]+)"')
TOKEN_FILE = re.compile(r"^google[a-z0-9]+\.html$", re.IGNORECASE)

# The structured-data block, and the site URL it names about itself. The node's
# own "url" is the prefix every other URL in the block hangs off, which is what
# makes the re-root below a prefix replacement rather than a list of paths.
LD_BLOCK = re.compile(r'(<script\s+type="application/ld\+json">)(.*?)(</script>)', re.DOTALL)
LD_NODE_URL = re.compile(r'"@type"\s*:\s*"(WebSite|SoftwareApplication)".*?"url"\s*:\s*"([^"]+)"',
                         re.DOTALL)

ROBOTS_TEMPLATE = """\
# GoaSynth — {base}
#
# Everything served from here is meant to be found: the landing page, the four
# legal pages, the screenshots and the published checksums. There is no private
# area, no admin route and no duplicate host to keep out, so the whole tree is
# crawlable. Access control is not what this file does: if a /private/ or
# /orders/ folder is ever served from docs/, add a Disallow for it below - and
# a note saying why - rather than assuming it is hidden.
#
# Generated by tools/make-site-index.py from the canonical link in each page.
# Edit that, not this.

User-agent: *
Allow: /

Sitemap: {base}sitemap.xml
"""

SITEMAP_TEMPLATE = """\
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Every page the site publishes, under the one origin it is canonical on.

  Generated by tools/make-site-index.py from the <link rel="canonical"> in each
  page. The pages are the source of truth for their own address, so this list
  cannot advertise a URL the site does not serve, or forget one it does.

  No <lastmod>: the date would be a guess that rots the moment a page is
  edited. <priority> and <changefreq> are ignored by search engines, so they
  are not written either.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{entries}
</urlset>
"""


def die(message: str) -> None:
    print(f"make-site-index: {message}", file=sys.stderr)
    raise SystemExit(1)


def origin_of(url: str) -> str:
    scheme, _, rest = url.partition("://")
    return f"{scheme}://{rest.split('/', 1)[0]}"


def read_pages() -> list[tuple[str, str]]:
    """(relative path, canonical URL) for every published page, in a fixed order."""
    if not DOCS.is_dir():
        die(f"no such folder: {DOCS}")

    found: list[tuple[str, str]] = []

    for path in sorted(DOCS.rglob("*.html")):
        rel = path.relative_to(DOCS).as_posix()

        # A verification token, not a page: it must sit at the site root, and it
        # has no canonical and no place in the sitemap.
        if TOKEN_FILE.match(path.name) and "/" not in rel:
            continue

        urls = CANONICAL.findall(path.read_text(encoding="utf-8"))

        if not urls:
            die(f"docs/{rel} has no <link rel=\"canonical\"> - a page that does not "
                f"say where it lives cannot be listed, and a crawler would index it "
                f"under every address it is reachable at")

        if len(urls) > 1:
            die(f"docs/{rel} declares {len(urls)} canonical links - there must be "
                f"exactly one, or the sitemap would have to pick one for you")

        if not urls[0].startswith("https://"):
            die(f"docs/{rel} declares the canonical {urls[0]!r}, which is not an "
                f"absolute https:// URL - a relative canonical is not a canonical")

        found.append((rel, urls[0]))

    if not found:
        die("no pages found under docs/ - nothing to write")

    return found


def site_base(pages: list[tuple[str, str]]) -> str:
    """The canonical address of the site root: what robots.txt and the sitemap hang off."""
    for rel, url in pages:
        if rel == "index.html":
            if not url.endswith("/"):
                die(f"docs/index.html declares the canonical {url!r} - the site root "
                    f"must end in a slash, or the sitemap URL beside it would be wrong")
            return url

    die("docs/index.html is missing - it is the page whose canonical gives the "
        "site root its address")


def rewrite_meta(text: str, key_is: str, key: str, value: str, rel: str) -> tuple[str, int]:
    """Set content="..." on every <meta> tag matching this property/name.

    Attribute order is not assumed: the tag is matched as a whole and only its
    content attribute is replaced, so anything else about it survives untouched.
    """
    tag = re.compile(r'<meta\s[^>]*\b' + key_is + r'="' + re.escape(key) + r'"[^>]*>')
    changed = 0

    def replace(match: re.Match[str]) -> str:
        nonlocal changed
        updated, n = re.subn(r'content="[^"]*"', f'content="{value}"', match.group(0))

        if n != 1:
            die(f"docs/{rel}: a <meta {key_is}=\"{key}\"> tag has no content=\"...\" "
                f"to rewrite - fix the tag, not this tool")

        changed += n
        return updated

    return tag.sub(replace, text), changed


def old_site_base(block: str, rel: str) -> str:
    """The address the JSON-LD block currently thinks the site lives at."""
    found = LD_NODE_URL.findall(block)

    for wanted in ("WebSite", "SoftwareApplication"):
        for node_type, url in found:
            if node_type != wanted:
                continue

            if not url.startswith("https://"):
                die(f"docs/{rel}: the JSON-LD {wanted} node names the site URL "
                    f"{url!r}, which is not absolute - nothing can be re-rooted against it")

            return url

    die(f"docs/{rel}: the JSON-LD block names no site URL - expected a "
        f"\"@type\": \"WebSite\" node with a \"url\" to re-root the other URLs against")


def rehome_jsonld(text: str, rel: str, base: str) -> str:
    """Re-root every URL inside the page's JSON-LD block.

    The block is parsed before and after, so a rewrite can never leave invalid
    structured data behind - a syntax error there costs the rich result and is
    invisible on the page.
    """
    match = LD_BLOCK.search(text)

    if not match:
        return text                     # a page with no structured data has none

    block = match.group(2)

    try:
        json.loads(block)
    except json.JSONDecodeError as exc:
        die(f"docs/{rel}: the JSON-LD block is not valid JSON ({exc}) - fix the block "
            f"before its URLs can be re-rooted")

    old = old_site_base(block, rel)

    if old == base:
        return text

    updated = block.replace(old, base)

    try:
        json.loads(updated)
    except json.JSONDecodeError as exc:      # pragma: no cover - a guard, not a path
        die(f"docs/{rel}: re-rooting the JSON-LD from {old} to {base} produced invalid "
            f"JSON ({exc}) - refusing to write it")

    return text[:match.start(2)] + updated + text[match.end(2):]


def rehome_head(rel: str, canonical: str, base: str) -> str:
    """The page, with the absolute URLs in its head and JSON-LD re-derived."""
    text = (DOCS / rel).read_text(encoding="utf-8")
    image = base + SITE_IMAGE

    text, urls = rewrite_meta(text, "property", "og:url", canonical, rel)

    if urls == 0:
        die(f"docs/{rel} has no <meta property=\"og:url\"> - every page needs one, "
            f"pointing at its own canonical, or a shared link resolves to whatever "
            f"address it was shared at")

    if urls > 1:
        die(f"docs/{rel} declares {urls} og:url values - there must be exactly one")

    text, _ = rewrite_meta(text, "property", "og:image", image, rel)
    text, _ = rewrite_meta(text, "name", "twitter:image", image, rel)

    return rehome_jsonld(text, rel, base)


def build(pages: list[tuple[str, str]]) -> tuple[str, str, str]:
    origins = sorted({origin_of(url) for _, url in pages})

    if len(origins) > 1:
        die("the pages disagree about where the site lives: " + ", ".join(origins)
            + " - sitemap.xml can only advertise one origin, so fix the pages first")

    base = site_base(pages)

    entries = "\n".join(
        f"  <url>\n    <loc>{url}</loc>\n  </url>\n" for _, url in pages
    )

    return (
        ROBOTS_TEMPLATE.format(base=base),
        SITEMAP_TEMPLATE.format(entries=entries),
        base,
    )


def write_if_changed(path: Path, text: str, check: bool, label: str) -> bool:
    """True when the file had to change (or, in --check mode, would have to)."""
    current = path.read_text(encoding="utf-8") if path.exists() else None

    if current == text:
        print(f"  {label:<24} already current")
        return False

    if check:
        state = "missing" if current is None else "out of date"
        print(f"  {label:<24} {state}")
        return True

    # newline="\n" so a Windows checkout does not turn these into CRLF and make
    # every run look like a change.
    path.write_text(text, encoding="utf-8", newline="\n")
    print(f"  {label:<24} {'written' if current is None else 'rewritten'}")
    return True


def main() -> int:
    args = sys.argv[1:]

    if any(a not in ("--check",) for a in args):
        die("usage: make-site-index.py [--check]")

    check = "--check" in args

    print("make-site-index: rebuilding the crawl files and the page URLs\n")

    pages = read_pages()
    robots, sitemap, base = build(pages)

    print(f"  {len(pages)} page(s) under docs/, all on {base}")

    changed = [
        write_if_changed(ROBOTS, robots, check, "docs/robots.txt"),
        write_if_changed(SITEMAP, sitemap, check, "docs/sitemap.xml"),
    ]

    for rel, canonical in pages:
        changed.append(write_if_changed(DOCS / rel, rehome_head(rel, canonical, base),
                                        check, f"docs/{rel}"))

    if check and any(changed):
        print("\nThe files do not match the pages. Run this without --check to "
              "rewrite them.", file=sys.stderr)
        return 1

    if not any(changed):
        print("\nNothing to do: the crawl files and every page URL already agree "
              "with the pages' canonical links.")
    else:
        print("\nCommit the changed files: search engines read them from the "
              "deployed site, so they only count once they are pushed.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
