#!/usr/bin/env python3
"""Generate docs/robots.txt and docs/sitemap.xml from the pages that exist.

Two files answer the same question - what is published here, and at which
address? - and a hand-written answer goes wrong quietly: a page added without a
sitemap entry is a page nobody crawls, and a host changed in one file but not
the others splits the site across two origins. Neither file is written by hand
any more:

    python tools/make-site-index.py           # rewrite them if they drifted
    python tools/make-site-index.py --check   # fail if they would change

Where the facts come from
-------------------------
The pages say where they live. Every .html file under docs/ declares its own
address in <link rel="canonical">, and those declarations are the only input:
sitemap.xml lists exactly them, and the Sitemap: line in robots.txt names the
sitemap beside the canonical of the site root. So a new page is picked up by
being a page - its canonical link is the thing that puts it on the list - and
there is no second list to keep in step.

Search-engine verification files (google*.html) are tokens, not pages: they are
skipped here, and they belong in no sitemap.

What it refuses
---------------
  * a page with no canonical link, or with more than one;
  * a canonical that is not an absolute https:// URL;
  * pages claiming two different origins - the sitemap can only advertise one,
    so that is a page to fix, not a sitemap to guess at;
  * a missing docs/index.html, or a docs/ with no pages in it.

The output is deterministic - sorted, LF endings, no timestamps - so re-running
it over an unchanged tree rewrites identical bytes and says so. tests/DocsCheck
compares the same three files during the test suite; this tool exists so that a
failure is a one-command fix rather than a hand edit.

Plain Python 3, no third-party modules, nothing to install.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
ROBOTS = DOCS / "robots.txt"
SITEMAP = DOCS / "sitemap.xml"

CANONICAL = re.compile(r'<link\s+rel="canonical"\s+href="([^"]+)"')
TOKEN_FILE = re.compile(r"^google[a-z0-9]+\.html$", re.IGNORECASE)

ROBOTS_TEMPLATE = """\
# GoaSynth — {base}
#
# Everything served from here is meant to be found: the landing page, the four
# legal pages, the screenshots and the published checksums. There is no private
# area, no admin route and no duplicate host to keep out, so the whole tree is
# crawlable. Access control is not what this file does: if a /private/ or
# /orders/ folder is ever served from docs/, add a Disallow for it below - and
# a note saying why - rather than assuming it is hidden.
#
# Generated by tools/make-site-index.py from the canonical link in each page.
# Edit that, not this.

User-agent: *
Allow: /

Sitemap: {base}sitemap.xml
"""

SITEMAP_TEMPLATE = """\
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Every page the site publishes, under the one origin it is canonical on.

  Generated by tools/make-site-index.py from the <link rel="canonical"> in each
  page. The pages are the source of truth for their own address, so this list
  cannot advertise a URL the site does not serve, or forget one it does.

  No <lastmod>: the date would be a guess that rots the moment a page is
  edited. <priority> and <changefreq> are ignored by search engines, so they
  are not written either.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{entries}
</urlset>
"""


def die(message: str) -> None:
    print(f"make-site-index: {message}", file=sys.stderr)
    raise SystemExit(1)


def origin_of(url: str) -> str:
    scheme, _, rest = url.partition("://")
    return f"{scheme}://{rest.split('/', 1)[0]}"


def read_pages() -> list[tuple[str, str]]:
    """(relative path, canonical URL) for every published page, in a fixed order."""
    if not DOCS.is_dir():
        die(f"no such folder: {DOCS}")

    found: list[tuple[str, str]] = []

    for path in sorted(DOCS.rglob("*.html")):
        rel = path.relative_to(DOCS).as_posix()

        # A verification token, not a page: it must sit at the site root, and it
        # has no canonical and no place in the sitemap.
        if TOKEN_FILE.match(path.name) and "/" not in rel:
            continue

        urls = CANONICAL.findall(path.read_text(encoding="utf-8"))

        if not urls:
            die(f"docs/{rel} has no <link rel=\"canonical\"> - a page that does not "
                f"say where it lives cannot be listed, and a crawler would index it "
                f"under every address it is reachable at")

        if len(urls) > 1:
            die(f"docs/{rel} declares {len(urls)} canonical links - there must be "
                f"exactly one, or the sitemap would have to pick one for you")

        if not urls[0].startswith("https://"):
            die(f"docs/{rel} declares the canonical {urls[0]!r}, which is not an "
                f"absolute https:// URL - a relative canonical is not a canonical")

        found.append((rel, urls[0]))

    if not found:
        die("no pages found under docs/ - nothing to write")

    return found


def site_base(pages: list[tuple[str, str]]) -> str:
    """The canonical address of the site root: what robots.txt and the sitemap hang off."""
    for rel, url in pages:
        if rel == "index.html":
            if not url.endswith("/"):
                die(f"docs/index.html declares the canonical {url!r} - the site root "
                    f"must end in a slash, or the sitemap URL beside it would be wrong")
            return url

    die("docs/index.html is missing - it is the page whose canonical gives the "
        "site root its address")


def build(pages: list[tuple[str, str]]) -> tuple[str, str, str]:
    origins = sorted({origin_of(url) for _, url in pages})

    if len(origins) > 1:
        die("the pages disagree about where the site lives: " + ", ".join(origins)
            + " - sitemap.xml can only advertise one origin, so fix the pages first")

    base = site_base(pages)

    entries = "\n".join(
        f"  <url>\n    <loc>{url}</loc>\n  </url>\n" for _, url in pages
    )

    return (
        ROBOTS_TEMPLATE.format(base=base),
        SITEMAP_TEMPLATE.format(entries=entries),
        origins[0],
    )


def write_if_changed(path: Path, text: str, check: bool) -> bool:
    """True when the file had to change (or, in --check mode, would have to)."""
    current = path.read_text(encoding="utf-8") if path.exists() else None

    if current == text:
        print(f"  docs/{path.name:<12} already current")
        return False

    if check:
        state = "missing" if current is None else "out of date"
        print(f"  docs/{path.name:<12} {state}")
        return True

    # newline="\n" so a Windows checkout does not turn these into CRLF and make
    # every run look like a change.
    path.write_text(text, encoding="utf-8", newline="\n")
    print(f"  docs/{path.name:<12} {'written' if current is None else 'rewritten'}")
    return True


def main() -> int:
    check = "--check" in sys.argv[1:]

    if check and any(a not in ("--check",) for a in sys.argv[1:]):
        die("usage: make-site-index.py [--check]")

    print("make-site-index: rebuilding the crawl files from the pages\n")

    pages = read_pages()
    robots, sitemap, origin = build(pages)

    print(f"  {len(pages)} page(s) under docs/, all on {origin}")

    changed = [
        write_if_changed(ROBOTS, robots, check),
        write_if_changed(SITEMAP, sitemap, check),
    ]

    if check and any(changed):
        print("\nThe crawl files do not match the pages. Run this without --check "
              "to rewrite them.", file=sys.stderr)
        return 1

    if not any(changed):
        print("\nNothing to do: robots.txt and sitemap.xml already list exactly "
              "the pages that exist.")
    else:
        print("\nCommit the two files: search engines read them from the deployed "
              "site, so they only count once they are pushed.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
