#!/usr/bin/env python3
"""Publish buyer reviews from the store into the site, with their average.

    python tools/make-reviews.py           # write the section and the rating
    python tools/make-reviews.py --check   # fail if they are out of date

Two things appear in docs/index.html, and they always agree because one run
writes both:

  * a "Reviews" section, between <!-- reviews:begin --> and <!-- reviews:end -->,
    showing each review, the average and the count as text. Google's review
    snippet guidelines require the marked-up reviews to be visible on the page
    that carries the markup, and the aggregate with them;
  * aggregateRating inside the SoftwareApplication JSON-LD, which is what turns
    the result into stars.

The store is Fulfil/reviews.json - seller-side, and deliberately gitignored,
because it holds buyers' email addresses and order references and this
repository is public. Fulfil/REVIEWS.md documents the capture process, what a
buyer has to have agreed to, and the Google rules this file is built around.

Ratings are computed as a whole number of tenths, with halves rounded up, and
tests/DocsCheck.cpp computes the same thing the same way - a mean of exactly
4.25 must not read 4.2 in one place and 4.3 in the other.

What it refuses
---------------
  * a rating that is not a whole number from 1 to 5;
  * a missing name, text or date, or a name longer than Google's 100 characters;
  * a date that is not ISO YYYY-MM-DD;
  * a review marked consent: false that the store expects to be published (it is
    skipped, not failed) - and a page whose section is out of date;
  * a page whose reviews section exists while the store is missing: the run
    cannot know what was withdrawn, so it stops rather than silently deleting
    published reviews.

Plain Python 3, no third-party modules, nothing to install.
"""
from __future__ import annotations

import html
import json
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX_HTML = ROOT / "docs" / "index.html"
STORE = ROOT / "Fulfil" / "reviews.json"

BEGIN = "<!-- reviews:begin — generated by tools/make-reviews.py; edit that, not this -->"
END = "<!-- reviews:end -->"

# Where the section goes when it appears for the first time: immediately before
# the closing call to action, so the last thing read before the buy button is
# what buyers said.
ANCHOR = "  <!-- ================= CTA ================= -->"

MANY = re.compile(r"[ \t\r\n]+")

LD_BLOCK = re.compile(r'(<script\s+type="application/ld\+json">)(.*?)(</script>)', re.DOTALL)

MONTHS = ["January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"]

MAX_NAME = 100            # Google: longer than this and the page is not eligible


def die(message: str) -> None:
    print(f"make-reviews: {message}", file=sys.stderr)
    raise SystemExit(1)


def rel(path: Path) -> str:
    """A path as the reader sees it - relative to the repository when it can be.

    relative_to() raises for a path outside the tree, and an error message is the
    worst place to find that out.
    """
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


# ---------------------------------------------------------------------------
def slug(value: object, where: str) -> str:
    """One line of text, HTML-escaped, ready for a page."""
    if not isinstance(value, str):
        die(f"{where}: expected text, got {type(value).__name__}")

    text = MANY.sub(" ", value).strip()

    if not text:
        die(f"{where}: empty")

    return html.escape(text, quote=True)


def whole_number(value: object, where: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        die(f"{where}: expected a whole number, got {value!r}")

    if not 1 <= value <= 5:
        die(f"{where}: {value} is not a rating from 1 to 5")

    return value


def review_day(value: object, where: str) -> date:
    if not isinstance(value, str):
        die(f"{where}: expected a date as \"YYYY-MM-DD\"")

    try:
        return date.fromisoformat(value.strip())
    except ValueError:
        die(f"{where}: {value!r} is not an ISO YYYY-MM-DD date - the section shows a real "
            f"date, and one guessed from a parse is worse than none")


def load_store() -> list[dict]:
    """Every review the buyer has agreed to have published, newest first."""
    if not STORE.exists():
        return []

    try:
        data = json.loads(STORE.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        die(f"{rel(STORE)} is not valid JSON ({exc})")

    if not isinstance(data, dict) or not isinstance(data.get("reviews"), list):
        die(f"{rel(STORE)}: expected an object with a \"reviews\" array - see "
            f"Fulfil/REVIEWS.md for the shape")

    published = []
    skipped = 0

    for index, entry in enumerate(data["reviews"], 1):
        where = f"{rel(STORE)} review {index}"

        if not isinstance(entry, dict):
            die(f"{where}: expected an object")

        if entry.get("consent") is not True:
            skipped += 1                      # never asked, or withdrew the ask
            continue

        name = slug(entry.get("name"), f"{where} name")

        if len(name) > MAX_NAME:
            die(f"{where} name: {len(name)} characters - longer than {MAX_NAME} and the "
                f"review becomes ineligible for a snippet")

        text = slug(entry.get("text"), f"{where} text")
        day = review_day(entry.get("date"), f"{where} date")
        rating = whole_number(entry.get("rating"), f"{where} rating")
        incentive = slug(entry.get("incentive"), f"{where} incentive") \
            if entry.get("incentive") else ""

        published.append({"name": name, "rating": rating, "day": day,
                          "text": text, "incentive": incentive})

    if skipped:
        print(f"  {skipped} review(s) in the store without consent - left unpublished")

    published.sort(key=lambda r: (r["day"], r["name"]), reverse=True)
    return published


def tenths(reviews: list[dict]) -> int:
    """The average rating, in tenths, halves rounded up.

    Deliberately integer arithmetic: tests/DocsCheck.cpp repeats this exact
    formula, and two floating-point roundings of the same mean is exactly how a
    guard starts failing on 4.25. Change one and you must change both.
    """
    count = len(reviews)
    total = sum(r["rating"] for r in reviews)
    return (total * 20 + count) // (2 * count)


def readable(day: date) -> str:
    return f"{day.day} {MONTHS[day.month - 1]} {day.year}"


def stars(rating: int) -> str:
    return "★" * rating + "☆" * (5 - rating)


# ---------------------------------------------------------------------------
def render_section(reviews: list[dict]) -> str:
    value = tenths(reviews)
    average = f"{value // 10}.{value % 10}"
    count = len(reviews)

    # The copy is read by readers, not just by a guard: "from 3 buyers who both
    # bought" is the sort of thing that makes a page look generated, so the
    # sentences have to work at every count including one.
    noun = "buyer" if count == 1 else "buyers"
    both = "" if count == 1 else "all "

    cards = []

    for review in reviews:
        disclosure = ""

        if review["incentive"]:
            # Google, 24 July 2026: an incentivized review must disclose it
            # clearly and prominently, or the markup is against the guidelines.
            disclosure = (f'\n            <p class="review-disclosure">'
                          f'{review["incentive"]}</p>')

        cards.append(
            f'        <article class="review" data-rating="{review["rating"]}" '
            f'data-incentive="{"true" if review["incentive"] else "false"}">\n'
            f'          <p class="review-stars" aria-label="{review["rating"]} out of 5">'
            f'{stars(review["rating"])}</p>\n'
            f'          <blockquote class="review-text"><p>{review["text"]}</p></blockquote>\n'
            f'          <p class="review-by"><b>{review["name"]}</b>'
            f'<span>{readable(review["day"])}</span></p>{disclosure}\n'
            f'        </article>'
        )

    return "\n".join([
        f"  {BEGIN}",
        '  <section class="section alt" id="reviews">',
        '    <div class="wrap">',
        '      <header class="section-head">',
        '        <p class="kicker">Reviews</p>',
        '        <h2>What buyers say</h2>',
        '        <p class="section-lede">',
        f'          <b data-review-average>{average}</b> out of 5, from '
        f'<b data-review-count>{count}</b> {noun} who {both}bought a licence and agreed to be '
        f'quoted here. Every review below is theirs, unedited in substance, and nothing on this '
        f'page is averaged in from anywhere else.',
        '        </p>',
        '      </header>',
        '',
        '      <div class="review-grid">',
        "\n".join(cards),
        '      </div>',
        '    </div>',
        '  </section>',
        f"  {END}",
    ])


def aggregate_node(reviews: list[dict]) -> dict:
    value = tenths(reviews)

    return {
        "@type": "AggregateRating",
        "ratingValue": round(value / 10, 1),
        "ratingCount": len(reviews),
        "reviewCount": len(reviews),
        "bestRating": 5,
        "worstRating": 1,
    }


# ---------------------------------------------------------------------------
def write_section(page: str, section: str | None) -> tuple[str, bool]:
    """Insert, replace or remove the generated section. Returns (page, changed)."""
    pattern = re.compile(r"(?s)[ \t]*" + re.escape(BEGIN) + r".*?" + re.escape(END) + r"[ \t]*")
    existing = pattern.search(page)

    if section is None:
        # Consent withdrawn, or the store emptied: the section has to go, and so
        # does the rating it was backing.
        if not existing:
            return page, False

        trimmed = page[:existing.start()] + page[existing.end():]

        # Removal leaves the blank line the insertion added, in front of the CTA.
        # Collapsing a run of three newlines to two is safe here and provably
        # inert elsewhere: index.html never has two blank lines in a row.
        return re.sub(r"\n{3,}", "\n\n", trimmed), True

    if existing:
        if existing.group(0).strip("\n") == section.strip("\n"):
            return page, False

        return (page[:existing.start()] + section + page[existing.end():]), True

    if ANCHOR not in page:
        die(f"docs/index.html has no \"{ANCHOR.strip()}\" anchor to put the reviews section "
            f"before - if the closing CTA was renamed, update ANCHOR in this tool")

    return page.replace(ANCHOR, section + "\n\n" + ANCHOR, 1), True


def write_aggregate(page: str, reviews: list[dict]) -> tuple[str, bool]:
    """Set or clear aggregateRating on the SoftwareApplication node."""
    match = LD_BLOCK.search(page)

    if not match:
        die("docs/index.html has no JSON-LD block for the aggregate rating to live in")

    block = match.group(2)

    try:
        data = json.loads(block)
    except json.JSONDecodeError as exc:
        die(f"docs/index.html: the JSON-LD block is not valid JSON ({exc})")

    nodes = data.get("@graph", [data])
    app = None

    for node in nodes if isinstance(nodes, list) else [nodes]:
        if isinstance(node, dict) and node.get("@type") == "SoftwareApplication":
            app = node

    if app is None:
        die("docs/index.html: the JSON-LD block has no SoftwareApplication node to rate")

    if reviews:
        wanted = aggregate_node(reviews)
    else:
        wanted = None

    if app.get("aggregateRating") == wanted:
        return page, False                       # nothing to do, and no reformat churn

    if wanted is None:
        app.pop("aggregateRating", None)
    else:
        app["aggregateRating"] = wanted

    updated = "\n" + json.dumps(data, indent=2, ensure_ascii=False) + "\n"

    return page[:match.start(2)] + updated + page[match.end(2):], True


# ---------------------------------------------------------------------------
def main() -> int:
    args = sys.argv[1:]

    if any(a not in ("--check",) for a in args):
        die("usage: make-reviews.py [--check]")

    check = "--check" in args

    print("make-reviews: publishing what buyers agreed to have quoted\n")

    reviews = load_store()
    page = INDEX_HTML.read_text(encoding="utf-8")
    published_already = BEGIN in page

    if not STORE.exists() and published_already:
        die("docs/index.html has a published reviews section but Fulfil/reviews.json is "
            "missing - the run cannot tell which reviews were withdrawn, so it will not "
            "delete them on a guess. Restore the store, or remove the section by hand.")

    if not reviews:
        print("  no reviews to publish" if STORE.exists() else "  no review store yet")
        section = None
    else:
        count = len(reviews)
        value = tenths(reviews)
        print(f"  {count} review(s) with consent, average {value // 10}.{value % 10}")

        section = render_section(reviews)

    page, section_changed = write_section(page, section)
    page, jsonld_changed = write_aggregate(page, reviews)

    changed = section_changed or jsonld_changed
    state = lambda flag, what: print(f"  {what:<28} {'updated' if flag else 'already current'}")

    if check:
        print(f"  {'docs/index.html':<28} {'out of date' if changed else 'already current'}")

        if changed:
            print("\nThe published reviews do not match the store. Run this without --check.",
                  file=sys.stderr)
            return 1

        return 0

    if not changed:
        print(f"  {'docs/index.html':<28} already current")
        print("\nNothing to do: the page and the store already agree.")
        return 0

    INDEX_HTML.write_text(page, encoding="utf-8", newline="\n")
    state(section_changed, "reviews section")
    state(jsonld_changed, "aggregateRating")

    print("\nCommit docs/index.html: the section and the rating are what the deployed page "
          "shows, and what Google reads.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
