#include "License.h"

#include <juce_cryptography/juce_cryptography.h>

#include "LicenseKeys.h"     // generated by GoaSynthKeygen --init (gitignored)

//==============================================================================
// Serial format
//   Master :  the raw master key, typed as-is (verified against a stretched,
//             salted SHA-256 digest embedded in the binary)
//   Normal :  GOA1-<machineId, 20 hex>-<RSA/2048 signature, hex, 512 chars>
//
// The signature signs SHA-256 of the machine-id string. The plugin embeds only
// the RSA public key (LicenseKeys.h); the private key lives exclusively in the
// GoaSynthKeygen tool. A serial only activates on the machine whose id it
// carries, and the machine ledger blocks a serial from ever being used on a
// second machine — sharing keys between people is blocked by construction.
//
namespace
{
// Fallback constants for builds made before `GoaSynthKeygen --init` has run
// (CMake writes an empty LicenseKeys.h placeholder; the keygen fills it).
// LicenseKeys.h (gitignored, generated by the keygen) defines:
//   GOA_LICENSE_PUBLIC_KEY, GOA_MASTER_DIGEST, GOA_MASTER_STRETCH_ROUNDS.
// Do NOT add #ifndef fallbacks for them here: a macro that expands to a bare
// number would be expanded inside JUCE's own include guards and break the
// build in baffling ways.
#if ! __has_include ("LicenseKeys.h")
 #error "Source/LicenseKeys.h is missing. Run: GoaSynthKeygen --init"
#endif

// Test builds (GOA_TEST_BUILD, set by CMakeLists.txt for the test targets) swap
// in a throwaway master digest from tests/TestMasterKey.h, so the suite never
// has to reference the seller's real master key. Production builds define
// nothing here and use the digest from LicenseKeys.h unchanged.
#ifdef GOA_TEST_BUILD
 #include "TestMasterKey.h"
 #undef  GOA_MASTER_DIGEST
 #define GOA_MASTER_DIGEST GOA_TEST_MASTER_DIGEST
#endif

// The master key is verified by stretching a salted SHA-256 (GOA_MASTER_STRETCH_ROUNDS
// extra hash rounds) so the value stored in the binary cannot be replayed as a
// serial and an offline guess of the key is expensive.
juce::String sha256Hex (const void* data, size_t numBytes);
juce::String sha256Hex (const juce::String& text);

juce::String stretchedMasterDigest (const juce::String& rawKey)
{
    juce::String h = sha256Hex ("goa-master::" + rawKey);
    for (int i = 0; i < GOA_MASTER_STRETCH_ROUNDS; ++i)
        h = sha256Hex (h);
    return h.toUpperCase();
}

juce::RSAKey publicKey()
{
    static const juce::RSAKey k (GOA_LICENSE_PUBLIC_KEY);
    return k;
}

// ---- machine identity -------------------------------------------------------

juce::String machineSeed()
{
    juce::String s;
    s << juce::SystemStats::getComputerName() << "|"
      << juce::SystemStats::getFullUserName() << "|"
      << juce::SystemStats::getLogonName() << "|"
      << juce::SystemStats::getUniqueDeviceID() << "|";   // OS device fingerprint (e.g. MachineGuid)

    for (const auto& mac : juce::MACAddress::getAllAddresses())
        s << mac.toString() << ";";

    return s;
}

// Deterministic 20-hex-char machine id (10 bytes of SHA-256 over the seed).
juce::String idFromSeed (const juce::String& seed)
{
    const juce::SHA256 h (seed.toRawUTF8(), (size_t) seed.getNumBytesAsUTF8());
    return juce::String::toHexString (h.getRawData().getData(), 10, 0).toUpperCase();
}

juce::String sha256Hex (const void* data, size_t numBytes)
{
    return juce::SHA256 (data, numBytes).toHexString();
}

juce::String sha256Hex (const juce::String& text)
{
    return sha256Hex (text.toRawUTF8(), (size_t) text.getNumBytesAsUTF8());
}

// ---- RSA value bridge (hex <-> BigInteger) ----------------------------------
// Both plugin and keygen speak raw hex so the signed value is bit-exact on
// both sides. toString (16, 512) zero-pads to the full RSA/2048 width.

juce::BigInteger valueFromHex (const juce::String& hex)
{
    juce::BigInteger v;
    v.parseString (hex, 16);
    return v;
}

juce::String hexOfValue (const juce::BigInteger& v)
{
    return v.toString (16, 512).toLowerCase();
}

// ---- license file + machine ledger ------------------------------------------

// Test hooks: GOASYNTH_LICENSE_FILE / GOASYNTH_LEDGER_FILE redirect storage so
// the test suite never touches the real license data.
static juce::File envFileOverride (const char* name)
{
    const juce::String v = juce::SystemStats::getEnvironmentVariable (name, {});
    return v.isNotEmpty() ? juce::File (v) : juce::File();
}

juce::File licenseDir()  { return juce::File::getSpecialLocation (juce::File::userApplicationDataDirectory)
                                    .getChildFile ("GoaSynth").getChildFile ("License"); }
juce::File licenseFile()
{
    if (auto f = envFileOverride ("GOASYNTH_LICENSE_FILE"); f != juce::File())
        return f;
    return licenseDir().getChildFile ("license.txt");
}
juce::File ledgerFile()
{
    if (auto f = envFileOverride ("GOASYNTH_LEDGER_FILE"); f != juce::File())
        return f;
    // Machine-wide (C:\Users\Public\Documents\GoaSynth\License), so a second
    // Windows account on the same PC cannot re-activate a bound serial — the
    // ledger travels with the machine, not the account.
    return juce::File::getSpecialLocation (juce::File::commonDocumentsDirectory)
                .getChildFile ("GoaSynth").getChildFile ("License")
                .getChildFile ("machines.txt");
}
struct LedgerEntry { juce::String serialHash, machine; };

std::vector<LedgerEntry> readLedger (const juce::File& f)
{
    std::vector<LedgerEntry> entries;
    if (! f.existsAsFile())
        return entries;

    for (const auto& line : juce::StringArray::fromLines (f.loadFileAsString()))
    {
        auto toks = juce::StringArray::fromTokens (line.trim(), ",", "");
        if (toks.size() == 2 && toks[0].isNotEmpty() && toks[1].isNotEmpty())
            entries.push_back ({ toks[0].trim(), toks[1].trim() });
    }
    return entries;
}

void writeLedger (const juce::File& f, const std::vector<LedgerEntry>& entries)
{
    f.getParentDirectory().createDirectory();

    juce::String text;
    for (const auto& e : entries)
        text << e.serialHash << "," << e.machine << "\n";
    f.replaceWithText (text);
}

void bindMachine (const juce::String& serial, const juce::String& machine, const juce::File& f)
{
    auto entries = readLedger (f);
    const juce::String key = sha256Hex (serial);

    for (auto& e : entries)
    {
        if (e.serialHash == key)
        {
            e.machine = machine;
            writeLedger (f, entries);
            return;
        }
    }
    entries.push_back ({ key, machine });
    writeLedger (f, entries);
}

// Process-wide copy of the stored serial: the editor timer polls licensing
// state (trial badge) and a disk stat + read at 30 Hz is pure waste.
// activate()/deactivate()/writeLicense() keep it coherent.
static juce::String& storedSerialCache()
{
    static juce::String s;
    return s;
}

void writeLicense (const juce::String& serial)
{
    licenseDir().createDirectory();
    licenseFile().replaceWithText (serial);

    storedSerialCache() = serial;   // keep the process-wide cache in sync
}

// Deactivate must also lift THIS machine's ledger binding, otherwise a serial
// could never be re-sold or moved: the old machine's entry would keep blocking
// the new owner forever. Bindings of other machines are left untouched.
void removeMachineBinding (const juce::String& serial, const juce::String& machine, const juce::File& f)
{
    auto entries = readLedger (f);
    const juce::String key = sha256Hex (serial);

    bool changed = false;
    std::vector<LedgerEntry> kept;
    kept.reserve (entries.size());
    for (auto& e : entries)
    {
        if (e.serialHash == key && e.machine == machine)
            changed = true;                       // drop this binding
        else
            kept.push_back (e);
    }

    if (changed)
        writeLedger (f, kept);
}

// ---- 24 h trial --------------------------------------------------------------
// One trial per machine, kept outside the per-account roaming profile so a
// second Windows account can't reset it. GOASYNTH_TRIAL_FILE redirects it for
// the test suite.
juce::File trialFile()
{
    if (auto f = envFileOverride ("GOASYNTH_TRIAL_FILE"); f != juce::File())
        return f;
    return juce::File::getSpecialLocation (juce::File::commonDocumentsDirectory)
                .getChildFile ("GoaSynth").getChildFile ("License").getChildFile ("trial.txt");
}

juce::int64 trialStartCached = 0;            // 0 = not yet read from disk
bool trialStampWritten = false;              // stamp present in the process (test hook)

juce::int64 trialStartUnix()
{
    if (trialStartCached > 0)
        return trialStartCached;

    juce::int64 t = 0;
    const juce::File f = trialFile();
    if (f.existsAsFile())
        t = f.loadFileAsString().trim().getLargeIntValue();

    if (t <= 0 && ! trialStampWritten)   // first launch: stamp now
    {
        t = juce::Time::currentTimeMillis() / 1000;
        f.getParentDirectory().createDirectory();
        f.replaceWithText (juce::String (t));
        trialStampWritten = true;
    }

    trialStartCached = t;
    return t;
}


juce::int64 trialSecondsLeft()
{
    const juce::int64 elapsed = juce::Time::currentTimeMillis() / 1000 - trialStartUnix();
    return juce::jmax ((juce::int64) 0, goa::License::trialSeconds - elapsed);
}

} // namespace

namespace goa
{
// ---- trial -------------------------------------------------------------------

bool License::trialActive()
{
    if (isLicensed())
        return false;   // a real license supersedes the trial everywhere

    return trialSecondsLeft() > 0;
}

juce::String License::trialTimeLeft()
{
    if (isLicensed())
        return "active";
    const juce::int64 s = trialSecondsLeft();
    if (s <= 0)
        return "expired";
    const int h = (int) (s / 3600);
    const int m = (int) ((s % 3600) / 60);
    return juce::String (h) + " h " + juce::String (m) + " m";
}

// Test-only override storage (see License.h).
static juce::String& testIdOverride()
{
    static juce::String s;
    return s;
}

juce::String License::machineId()
{
    const juce::String& t = testIdOverride();
    if (t.isNotEmpty())
        return t;

    static const juce::String id = idFromSeed (machineSeed());
    jassert (id.length() == serialHexLength);
    return id;
}

void License::setTestMachineId (const juce::String& id)
{
    testIdOverride() = id;
}

void License::setTrialTestStart (juce::int64 unixSeconds)
{
    trialStartCached = (unixSeconds > 0 ? unixSeconds
                                        : juce::Time::currentTimeMillis() / 1000);
    trialFile().getParentDirectory().createDirectory();
    trialFile().replaceWithText (juce::String (trialStartCached));
    trialStampWritten = true;
}

bool License::masterMatches (const juce::String& serial)
{
    // The raw master key is typed straight into the serial box (no GOA1- prefix).
    if (serial.startsWith ("GOA1-") || serial.isEmpty())
        return false;

    const juce::String digest = juce::String (GOA_MASTER_DIGEST).toUpperCase();
    return digest.isNotEmpty() && stretchedMasterDigest (serial) == digest;
}

bool License::activate (const juce::String& serialIn, juce::String& error)
{
    const juce::String trimmed = serialIn.trim();
    error.clear();

    if (trimmed.isEmpty())
    {
        error = "Enter your serial key.";
        return false;
    }

    // Master key is checked on the case-preserved input: its verification
    // digest is case-sensitive, and mangling the case would reject it.
    if (masterMatches (trimmed))
    {
        bindMachine (trimmed, machineId(), ledgerFile());
        writeLicense ("GOA1-MASTER");   // never persist the raw master key
        return true;
    }

    // Serial format is hex + GOA1 prefix, so normalise case from here on.
    const juce::String serial = trimmed.toUpperCase();
    const juce::File ledger = ledgerFile();

    // ---- signed serial: verify signature + machine binding -----------------
    if (juce::String (GOA_LICENSE_PUBLIC_KEY).isNotEmpty())
    {
        const juce::String body = serial.startsWith ("GOA1-") ? serial.substring (5) : serial;
        const int dash = body.indexOfChar ('-');

        bool ok = dash == serialHexLength;
        juce::String id, sigHex;

        if (ok)
        {
            id     = body.substring (0, dash);
            sigHex = body.substring (dash + 1);

            if (id != machineId())
            {
                error = "This serial was issued for a different machine.\n"
                        "Send YOUR MACHINE ID to the seller to receive your own key.";
                return false;
            }

            juce::BigInteger sig = valueFromHex (sigHex);
            ok = publicKey().isValid() && ! sig.isZero() && publicKey().applyToValue (sig);

            if (ok)
            {
                // The decrypted value must equal SHA-256 of the machine id.
                const juce::MemoryBlock mb (id.toRawUTF8(), (size_t) id.getNumBytesAsUTF8());
                ok = (sig == valueFromHex (sha256Hex (mb.getData(), mb.getSize())));
            }
        }

        if (! ok)
        {
            error = "This serial is not valid for GoaSynth.";
            return false;
        }

        // ---- ledger: a serial already used on another machine is blocked --
        for (const auto& e : readLedger (ledger))
        {
            if (e.serialHash == sha256Hex (serial) && e.machine != machineId())
            {
                error = "This serial has already been used on another computer and is now blocked.";
                return false;
            }
        }

        bindMachine (serial, machineId(), ledger);
        writeLicense (serial);
        return true;
    }

    // No keypair embedded (build before --init): refuse everything but master.
    error = "Licensing is not configured in this build.";
    return false;
}

bool License::isLicensed()
{
    return storedSerial().isNotEmpty();
}

juce::String License::storedSerial()
{
    // Cached per process: the editor timer polls licensing state (trial badge)
    // and a disk stat + read at 30 Hz is waste. activate()/deactivate() keep
    // the cache coherent.
    static bool cached = false;
    if (! cached)
    {
        const juce::File f = licenseFile();
        storedSerialCache() = f.existsAsFile() ? f.loadFileAsString().trim() : juce::String();
        cached = true;
    }
    return storedSerialCache();
}

void License::deactivate()
{
    // Lift the ledger binding first, while we still know the serial.
    const juce::String serial = storedSerial();
    if (serial.startsWith ("GOA1-") && serial != "GOA1-MASTER")
        removeMachineBinding (serial, machineId(), ledgerFile());

    const juce::File f = licenseFile();
    if (f.existsAsFile())
        f.deleteFile();

    storedSerialCache() = {};
}

juce::String License::formatSerial (const juce::String& hex)
{
    const juce::String t = hex.removeCharacters ("-").toUpperCase();
    juce::String out;
    for (int i = 0, n = t.length(); i < n; i += 4)
    {
        if (i > 0) out << "-";
        out << t.substring (i, i + 4);
    }
    return out;
}

// ---- .goalicense files ------------------------------------------------------
//
// GOA-LICENSE-1 is a small text document the keygen exports for the buyer:
//
//   GOA-LICENSE-1
//   serial:  <RSA-signed serial, raw or dashed>
//   machine: <machine id the serial was issued for, informational>
//   note:    <free text, e.g. "John's studio PC">
//   issued:  <ISO-8601 timestamp, informational>
//
// The signature and the machine ledger make the informational lines cosmetic:
// any tampering with them cannot widen what the file can activate.
juce::String License::makeLicenseFile (const juce::String& serial, const juce::String& buyerNote,
                                       const juce::String& buyerName,
                                       const juce::String& buyerEmail)
{
    juce::StringArray body;

    // Canonical raw form: GOA1-<machineId 20>-<signature 512>. Strip every
    // dash, then rebuild exactly the two structural ones — the activate()
    // parser needs the GOA1 / id / signature boundaries.
    const juce::String flat = serial.trim().toUpperCase().removeCharacters ("-");
    juce::String compact = flat;
    if (flat.startsWith ("GOA1"))
        compact = "GOA1-" + flat.substring (4, 4 + serialHexLength)
                + "-"   + flat.substring (4 + serialHexLength);

    const juce::String machine = compact.startsWith ("GOA1-")
                                     ? compact.substring (5, 5 + serialHexLength)
                                     : juce::String ("-");
    const juce::String note = buyerNote.trim().replaceCharacters ("\r\n", "  ");
    const juce::String name  = buyerName.trim().replaceCharacters ("\r\n", "  ");
    const juce::String email = buyerEmail.trim().replaceCharacters ("\r\n", "  ");

    body.add (fileMagic);
    body.add ("serial:  " + compact);
    body.add ("machine: " + machine);
    body.add ("name:    " + (name.isEmpty()  ? juce::String ("-") : name));
    body.add ("email:   " + (email.isEmpty() ? juce::String ("-") : email));
    body.add ("note:    " + (note.isEmpty()  ? juce::String ("-") : note));
    body.add ("issued:  " + juce::Time::getCurrentTime().toISO8601 (true));
    body.add ("plugin:  GoaSynth VST3");
    body.add ("usage:   double-click this file (opens GoaSynth) or IMPORT it on the activation screen");

    return body.joinIntoString ("\n") + "\n";
}

bool License::activateFile (const juce::File& f, juce::String& error)
{
    error.clear();

    if (f == juce::File() || ! f.existsAsFile())
    {
        error = "License file not found.";
        return false;
    }

    const juce::String text = f.loadFileAsString();
    juce::String serial;

    for (const auto& line : juce::StringArray::fromLines (text))
    {
        const juce::String t = line.trim();
        if (t.startsWithIgnoreCase ("serial:"))
        {
            serial = t.fromFirstOccurrenceOf (":", false, false).trim();
            break;
        }
    }

    if (serial.isEmpty())
    {
        error = "This is not a GoaSynth license file (no serial line).";
        return false;
    }

    return activate (serial, error);
}

} // namespace goa
